In [1]:
#1
python --version
Python 3.8.5
# 2
pip install selenium
# 3
시계열 분석

SyntaxError: invalid syntax (<ipython-input-1-23e3f5610b9f>, line 3)

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('iris.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SepalLength  150 non-null    float64
 1   SepalWidth   150 non-null    float64
 2   PetalLength  150 non-null    float64
 3   PetalWidth   150 non-null    float64
 4   Name         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [7]:
x = df.drop('Name', axis=1)
y = df['Name']

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=19)
x_train.shape

(112, 4)

In [10]:
from sklearn import svm
svm_model = svm.SVC(kernel='rbf')
svm_model.fit(x_train, y_train)
y_hat = svm_model.predict(x_test)
print(y_hat[0:10])

['Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica']


In [11]:
from sklearn import metrics
svm_matrix = metrics.confusion_matrix(y_test, y_hat)
print(svm_matrix)

[[14  0  0]
 [ 0 14  0]
 [ 0  2  8]]


In [18]:
# 5
df = pd.DataFrame({'이름' : ['홍길동','이몽룡','김삿갓'],
                  '팀':['A','B','C']})
df = df.set_index('이름')
df = pd.get_dummies(df)
df

팀_A  팀_B  팀_C
이름                
홍길동    1    0    0
이몽룡    0    1    0
김삿갓    0    0    1