# numpy
- numerical python 약자
- 수치해석, 통계 관련 기본 모듈
- 다차원 배열 객체 제공

In [6]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)
print(type(a)) # 타입
print(a.shape) # 행열

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>
(3, 5)


4

In [7]:
a.ndim # 차원

2

In [8]:
a.dtype # 배열의 요소의 자료형

dtype('int32')

In [9]:
a.dtype.name # 자료형 의 이름

'int32'

In [10]:
a.itemsize # 배열요소의 크기, 바이트 // int32 자료형은 4바이트 값 저장함

4

In [11]:
a.size # a 배열의 요소의 갯수

15

In [13]:
a.data # 실제 저장된 요소의 버퍼부분 설정

In [12]:
b= np.array([6,7,8])
b

array([6, 7, 8])

In [14]:
type(b)

numpy.ndarray

In [15]:
b.data

In [16]:
c = np.array((6,7,8))
d = np.array([(1.5,2,3),(4,5,6)])
d

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
d.ndim

2

In [19]:
d.size

6

In [20]:
e = np.zeros((3,4))
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
f = np.ones((3,4)) # 3행4열 배열을 생성하고, 모든 값은 0으로 채움
f

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
g = np.arange(6)
g

array([0, 1, 2, 3, 4, 5])

In [32]:
h = np.arange(10000)
h = h.reshape(100,100)
print(h)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [34]:
j = np.linspace(0,2,9) # 0 부터 2까지 9개로 균등 분할 수 배열로 생성
j

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [36]:
np.pi # 원주율
# 0부터 원주율까지 수를 균등하게 분할해서 10를 배열로 생성
k = np.linspace(0, np.pi, 10)
k

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [38]:
m = np.sin(np.linspace(0, np.pi*2, 100))
m

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [39]:
m = np.sin(np.pi/2) # 라디안, np.pi/2 90도 ★
m

1.0

# 라디안, np.pi/2 90도 ★
- 원주율은 반지름으로 구한 원둘레
- 1라디안 : 1 반지름만큼 갔을때의 각도
- 전체둘레는 2*pi * r  = 360도
- pi는 180도
- pi/2는 90도

In [40]:
np.sin(np.pi/2) # 삼각함수

1.0

In [41]:
a = np.array([20,30,40,50,])
b = np.arange(4)
c = a-b
c

array([20, 29, 38, 47])

In [42]:
c = b**2
c

array([0, 1, 4, 9], dtype=int32)

In [44]:
c = a<35

In [45]:
c

array([ True,  True, False, False])

In [46]:
type(c)

numpy.ndarray

In [47]:
# 2차원 배열의 연산
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])
a*b #각위치 요소들간의 곱

array([[2, 0],
       [0, 4]])

In [48]:
a@b # 행렬의 곱 // 파이썬3.5이상

array([[5, 4],
       [3, 4]])

In [ ]:
a.dot(b) # 행렬 곱

In [49]:
# 난수 생성
rg = np.random.default_rng(1)
rg

Generator(PCG64) at 0x20E1478D130

In [53]:
a = np.ones((2,3), dtype=int) # 2행3열 배열, 1값을 초기화, 자료 정수형
b=rg.random((2,3)) # 1미만의 수를 2행3열짜리 난수
b

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [54]:
a* 
a

array([[1, 1, 1],
       [1, 1, 1]])

In [55]:
a*= 3 # a 배열에 요소들의 값을 *3을 한 값을 다시 a 배열에 대입
a

array([[3, 3, 3],
       [3, 3, 3]])

In [57]:
b += a # 각 요소에 a 를 더해줌
b

array([[3.82770259, 3.40919914, 3.54959369],
       [3.02755911, 3.75351311, 3.53814331]])

In [58]:
a += b # 이건 안됨 왜냐면 정수형은 실수형을 못 받음
a

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [62]:
c = np.arange(6).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
a+=c 
a

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [68]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3) 
c = a+b
c.dtype

dtype('float64')

In [70]:
# sum, min, max
rg=np.random.default_rng(1)
a = rg.random((2,3))
a

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [71]:
print('합', a.sum())
print('최소', a.min())
print('최대', a.max())

합 3.290252281866131
최소 0.14415961271963373
최대 0.9504636963259353
